/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import { HomePage as HomePage } from './components/home-page/home-page';

interface HTMLHomePageElement extends HomePage, HTMLElement {
}
declare var HTMLHomePageElement: {
  prototype: HTMLHomePageElement;
  new (): HTMLHomePageElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "home-page": HTMLHomePageElement;
  }
  interface ElementTagNameMap {
      "home-page": HTMLHomePageElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "home-page": JSXElements.HomePageAttributes;
      }
  }
  namespace JSXElements {
      export interface HomePageAttributes extends HTMLAttributes {
        
      }
  }
}

import { MyApp as MyApp } from './components/my-app/my-app';

interface HTMLMyAppElement extends MyApp, HTMLElement {
}
declare var HTMLMyAppElement: {
  prototype: HTMLMyAppElement;
  new (): HTMLMyAppElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-app": HTMLMyAppElement;
  }
  interface ElementTagNameMap {
      "my-app": HTMLMyAppElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-app": JSXElements.MyAppAttributes;
      }
  }
  namespace JSXElements {
      export interface MyAppAttributes extends HTMLAttributes {
        
      }
  }
}

import { Page1 as Page1 } from './components/page-1/page-1';

interface HTMLPage1Element extends Page1, HTMLElement {
}
declare var HTMLPage1Element: {
  prototype: HTMLPage1Element;
  new (): HTMLPage1Element;
};
declare global {
  interface HTMLElementTagNameMap {
      "page-1": HTMLPage1Element;
  }
  interface ElementTagNameMap {
      "page-1": HTMLPage1Element;
  }
  namespace JSX {
      interface IntrinsicElements {
          "page-1": JSXElements.Page1Attributes;
      }
  }
  namespace JSXElements {
      export interface Page1Attributes extends HTMLAttributes {
        
      }
  }
}

import { Page2 as Page2 } from './components/page-2/page-2';

interface HTMLPage2Element extends Page2, HTMLElement {
}
declare var HTMLPage2Element: {
  prototype: HTMLPage2Element;
  new (): HTMLPage2Element;
};
declare global {
  interface HTMLElementTagNameMap {
      "page-2": HTMLPage2Element;
  }
  interface ElementTagNameMap {
      "page-2": HTMLPage2Element;
  }
  namespace JSX {
      interface IntrinsicElements {
          "page-2": JSXElements.Page2Attributes;
      }
  }
  namespace JSXElements {
      export interface Page2Attributes extends HTMLAttributes {
        
      }
  }
}

